version: "3.9"


x-env: &default-env
  PROMETHEUS_URL: http://prometheus:9090
  TRAEFIK_DYNAMIC_PATH: /dynamic/traefik-dynamic.yml

services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "8080:8080"  # Traefik dashboard
      - "80:80"
    volumes:
      - ./ops/traefik/dynamic:/dynamic
    networks: [lab]
    # uncomment if you want these envs in the container:
    # environment: *default-env

  prometheus:
    image: prom/prometheus:v2.55.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/rules:/etc/prometheus/rules:ro
    networks: [lab]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    volumes:
      - ./ops/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks: [lab]

  grafana:
    image: grafana/grafana:11.1.4
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards
    networks: [lab]

networks:
  lab:
    driver: bridge
