global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-v1:8000", "api-v2:8000"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
