route:
  receiver: webhook_rollback
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 10m

receivers:
- name: webhook_rollback
  webhook_configs:
  - url: http://rollbacker:9099/alerts
    send_resolved: true
