name: deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint & Test
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          echo "(demo) tests pass"

      - name: Build images
        run: |
          docker build -t lab/api:v1 services/api/v1
          docker build -t lab/api:v2 services/api/v2

      - name: Security & Policy
        run: |
          docker run --rm -v "$PWD:/repo" aquasec/trivy:0.53.0 fs /repo || true
          docker run --rm -v "$PWD:/repo" bridgecrew/checkov checkov -f /repo/infra/main.tf -o cli || true

      - name: Bring up stack
        run: |
          docker compose up -d traefik prometheus alertmanager grafana api-v1 api-v2 rollbacker traffic
          sleep 30

      - name: Canary rollout
        run: |
          docker compose run --rm canary-controller python /app/controller.py || true

      - name: Collect artifacts
        if: always()
        run: |
          docker compose logs > compose.log

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: compose.log
